In [1]:
using Pkg
Pkg.activate(".")

  Activating environment at `C:\Users\gabri\Documents\Cadeiras\MAT55\MAT55_Exame\Project.toml`


In [2]:
Pkg.precompile()

Precompiling project...
  ✓ MAT55_Exame
  1 dependency successfully precompiled in 8 seconds (176 already precompiled)


In [3]:
using DataFrames
using LinearAlgebra
using Gadfly
using Statistics
using MAT55_Exame

In [4]:
df = create_returns()

HTTP.ExceptionRequest.StatusError(404, "GET", "/v7/finance/download/BRK.B?period1=1632096000&period2=1638735365&interval=1d&events=history", HTTP.Messages.Response:
"""
HTTP/1.1 404 Not Found
content-type: text/csv;charset=utf-8
vary: Origin
y-rid: 2s02t19gqqi1l
x-yahoo-request-id: 2s02t19gqqi1l
x-request-id: 7f7650da-3d50-48a1-99c5-8b465da20583
content-length: 52
x-envoy-upstream-service-time: 2
date: Sun, 05 Dec 2021 23:16:04 GMT
server: ATS
x-envoy-decorator-operation: finance-chart-api--mtls-production-bf1.finance-k8s.svc.yahoo.local:4080/*
Cache-Control: max-age=0, private
Expires: -1
Age: 1
Strict-Transport-Security: max-age=15552000
Referrer-Policy: no-referrer-when-downgrade
X-Frame-Options: SAMEORIGIN
Connection: keep-alive
Expect-CT: max-age=31536000, report-uri="http://csp.yahoo.com/beacon/csp?src=yahoocom-expect-ct-report-only"
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff

404 Not Found: No data found, symbol may be delisted""")HTTP.ExceptionRequest.Statu

53×504 DataFrame
 Row │ date        MMM           ABT          ABBV         ABMD          ACN   ⋯
     │ Date…       Float64       Float64      Float64      Float64       Float ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 2021-09-21  -0.0116878     0.00208212   0.00704887  -0.00688012   -0.00 ⋯
   2 │ 2021-09-22   0.00795874   -0.00383597  -0.00690619   0.0115076     0.01
   3 │ 2021-09-23   0.00939726    0.00521461   0.0089277    0.00472832    0.02
   4 │ 2021-09-24  -0.00269931   -0.00742219  -0.0027012   -0.000713043  -0.01
   5 │ 2021-09-27   0.00414273   -0.0304736    0.0060708   -0.0339365    -0.01 ⋯
   6 │ 2021-09-28  -0.00957143   -0.0152596   -0.00352771  -0.0212722    -0.03
   7 │ 2021-09-29   0.00460984    0.00606368   0.0139743   -0.00531282   -0.00
   8 │ 2021-09-30  -0.0301858    -0.0111335   -0.0089121   -0.012109     -0.01
   9 │ 2021-10-01   0.00718273   -0.00778801   0.0113098   -0.0067277     0.01 ⋯
  10 │ 2021-10-04  -0.00362237   -0.0143332   -0.00329996  -0.029258     -0.01
  11 │ 2021-10-05   0.0104522     0.0030295    0.00717372   0.0592602     0.01
  ⋮  │     ⋮            ⋮             ⋮            ⋮            ⋮              ⋱
  44 │ 2021-11-19   0.00257309   -0.00626765  -0.00708979  -0.000617349  -0.00
  45 │ 2021-11-22   0.0023992    -0.0124566   -0.00507567  -0.0137356    -0.01 ⋯
  46 │ 2021-11-23  -0.0011132    -0.00622704   0.0279291   -0.0212931    -0.00
  47 │ 2021-11-24  -0.0101973     0.00473969  -0.00185055   0.0292523     0.00
  48 │ 2021-11-26  -0.0118786     0.00647635  -0.018119    -0.0349339    -0.02
  49 │ 2021-11-29   0.00404508    0.0170798    0.0032615   -0.0210443     0.03 ⋯
  50 │ 2021-11-30  -0.0351246    -0.0176521   -0.0137736   -0.0135999    -0.02
  51 │ 2021-12-01   0.00405789    0.0077125    0.005465    -0.0288138     0.00
  52 │ 2021-12-02  -0.00275289    0.0129399    0.00828228   0.0220144     0.01
  53 │ 2021-12-03   0.013685      0.0147219    0.0169419   -0.0377992    -0.01 ⋯
                                                 499 columns and 32 rows omitted

In [5]:
# checar se há alguma correlação perfeita entre duas ações
correl = cor(Matrix(select(df, Not(:date))))
nodiag = correl - diagm(diag(correl))
findall(x -> x == 1.0, nodiag)

CartesianIndex{2}[]

In [10]:
μ, Σ, tickers, dates = get_statistics(df);

In [11]:
μ

503-element Vector{Float64}:
 -0.0007912048386208962
  0.0008775901386909208
  0.0021483278157683346
 -0.002495773326190809
  0.0016704969450775805
 -0.004998630311238285
 -0.0005207862274841264
  0.007042580060203213
  0.002162415575013979
 -2.169712351298996e-5
  0.0008723067494140589
 -0.0024793819527281383
  0.0021638703581336113
  ⋮
  0.0013431665350315007
  0.001654902863707309
  0.00042263705386406974
 -4.423527465701036e-5
  0.0005838079692177261
  0.0072651984992723245
 -0.0018460789403183823
 -6.93430205109394e-5
  0.0013823100157326624
 -0.0030802997713579076
  0.00218586839272067
  0.0022888492858123438

In [12]:
Σ

503×503 Matrix{Float64}:
  0.000115383   2.42916e-5    3.94242e-5   …  7.15073e-5    1.75785e-5
  2.42916e-5    0.000159504   2.90368e-5      1.29332e-5    6.4625e-5
  3.94242e-5    2.90368e-5    0.000120011     6.56096e-5    2.89609e-5
  4.88085e-5    3.44572e-5   -3.18874e-5      7.19786e-5    0.000101256
  6.75511e-5    5.06847e-5    3.44888e-5      7.22178e-5    0.00010186
  6.12645e-5    1.6472e-5    -1.67266e-6   …  1.85511e-5    3.51573e-5
  1.5862e-5     8.7252e-5    -5.15475e-6      5.04126e-5    0.000160229
 -2.77908e-6    6.4776e-5    -6.60539e-5      9.94711e-5    0.000146311
  6.18312e-5    4.29251e-5    4.57771e-5      0.000166196   3.43825e-5
  2.09922e-5    3.3586e-5     2.31242e-5      7.38541e-5    1.7389e-5
  7.44797e-5    1.10165e-5    2.11345e-5   …  0.000179498   5.73954e-6
  4.85739e-5    9.47536e-5    2.57372e-6      2.28556e-5    0.000112358
  6.26986e-5   -1.30599e-5    1.19714e-5      3.59951e-5    1.58455e-5
  ⋮                                        ⋱      

In [13]:
tickers

503-element Vector{String}:
 "MMM"
 "ABT"
 "ABBV"
 "ABMD"
 "ACN"
 "ATVI"
 "ADBE"
 "AMD"
 "AAP"
 "AES"
 "AFL"
 "A"
 "APD"
 ⋮
 "WHR"
 "WMB"
 "WLTW"
 "WYNN"
 "XEL"
 "XLNX"
 "XYL"
 "YUM"
 "ZBRA"
 "ZBH"
 "ZION"
 "ZTS"

In [14]:
dates

53×1 DataFrame
 Row │ date       
     │ Date…      
─────┼────────────
   1 │ 2021-09-21
   2 │ 2021-09-22
   3 │ 2021-09-23
   4 │ 2021-09-24
   5 │ 2021-09-27
   6 │ 2021-09-28
   7 │ 2021-09-29
   8 │ 2021-09-30
   9 │ 2021-10-01
  10 │ 2021-10-04
  11 │ 2021-10-05
  ⋮  │     ⋮
  44 │ 2021-11-19
  45 │ 2021-11-22
  46 │ 2021-11-23
  47 │ 2021-11-24
  48 │ 2021-11-26
  49 │ 2021-11-29
  50 │ 2021-11-30
  51 │ 2021-12-01
  52 │ 2021-12-02
  53 │ 2021-12-03
   32 rows omitted

In [16]:
n = size(Σ, 1)

503

In [18]:
A = [2 .* Σ ones(n); ones(n)' 0]

504×504 Matrix{Float64}:
  0.000230766   4.85833e-5    7.88485e-5   …  0.000143015   3.5157e-5    1.0
  4.85833e-5    0.000319008   5.80737e-5      2.58663e-5    0.00012925   1.0
  7.88485e-5    5.80737e-5    0.000240022     0.000131219   5.79217e-5   1.0
  9.7617e-5     6.89145e-5   -6.37749e-5      0.000143957   0.000202512  1.0
  0.000135102   0.000101369   6.89776e-5      0.000144436   0.000203719  1.0
  0.000122529   3.29441e-5   -3.34533e-6   …  3.71021e-5    7.03145e-5   1.0
  3.1724e-5     0.000174504  -1.03095e-5      0.000100825   0.000320458  1.0
 -5.55817e-6    0.000129552  -0.000132108     0.000198942   0.000292622  1.0
  0.000123662   8.58502e-5    9.15542e-5      0.000332392   6.8765e-5    1.0
  4.19845e-5    6.7172e-5     4.62485e-5      0.000147708   3.4778e-5    1.0
  0.000148959   2.2033e-5     4.2269e-5    …  0.000358995   1.14791e-5   1.0
  9.71478e-5    0.000189507   5.14745e-6      4.57113e-5    0.000224717  1.0
  0.000125397  -2.61198e-5    2.39429e-5      7.199

In [19]:
b = [zeros(n); 1]

504-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 1.0

In [20]:
z = inv(A) * b

504-element Vector{Float64}:
 -0.453125
 -0.265625
 -2.53125
  0.125
  0.1875
  0.18359375
 -0.265625
  0.171875
  0.28125
 -0.83984375
  1.2421875
 -1.5
 -0.125
  ⋮
  0.30859375
 -2.1484375
 -0.041015625
  0.203125
 -0.3544921875
 -1.1640625
 -0.53125
  0.34375
  0.154296875
  0.10546875
 -0.578125
 -4.573977915173222e-19

In [22]:
dot(z[1:503], ones(n))

-13.182533264160156

In [24]:
dists = Matrix(select(df, Not(:date)))
Σ2 = cov(dists, dims=1)

503×503 Matrix{Float64}:
  0.000115383   2.42916e-5    3.94242e-5   …  7.15073e-5    1.75785e-5
  2.42916e-5    0.000159504   2.90368e-5      1.29332e-5    6.4625e-5
  3.94242e-5    2.90368e-5    0.000120011     6.56096e-5    2.89609e-5
  4.88085e-5    3.44572e-5   -3.18874e-5      7.19786e-5    0.000101256
  6.75511e-5    5.06847e-5    3.44888e-5      7.22178e-5    0.00010186
  6.12645e-5    1.6472e-5    -1.67266e-6   …  1.85511e-5    3.51573e-5
  1.5862e-5     8.7252e-5    -5.15475e-6      5.04126e-5    0.000160229
 -2.77908e-6    6.4776e-5    -6.60539e-5      9.94711e-5    0.000146311
  6.18312e-5    4.29251e-5    4.57771e-5      0.000166196   3.43825e-5
  2.09922e-5    3.3586e-5     2.31242e-5      7.38541e-5    1.7389e-5
  7.44797e-5    1.10165e-5    2.11345e-5   …  0.000179498   5.73954e-6
  4.85739e-5    9.47536e-5    2.57372e-6      2.28556e-5    0.000112358
  6.26986e-5   -1.30599e-5    1.19714e-5      3.59951e-5    1.58455e-5
  ⋮                                        ⋱      

In [28]:
A = [2 .* Σ2 ones(n); ones(n)' 0]
z = A \ b
dot(z[1:503], ones(n))

1.0000000000000004

In [ ]:
function vetor_port(σ::Array{Float64,2})
    n = size[σ,1] 
    vec1 = ones(n)
    vec2 = [ones(n); 0.0]
    b = [zero(n); 1.0]

    top_A = hcat(2*σ,vec1)
    A = vcat(top_A,vec2)

    U, S, V = svd(A)

    S_1 = Diagonal(S)

    x = V*inv(S_1)*U'*b #Vetor dos portfólios e o λ (n lembro o nome kk)

    m = x[1:n-1] # Vetor do peso dos portfólios para a menor variância global

end

In [ ]:
function gmin(μ::Array{Float64,1},m::Array{Float64,1})

    # Valor esperado para o vetor m
    μ_gmin = dot(m,μ)

    # Desvio padrão do vetor M
    σ_gmin2 = m'*σ*m
    σ_gmin = sqrt(σ_gmin2)

end

In [ ]:
function grafico1(μ::Array{Float64,1}, σ::Array{Float64,2})

    σ_vec = sqrt.(diag(σ))

    xvec = ones(3)/3      # Vetor de pesos X
    μ_x = dot(xvec, μ)
    σ_x2= xvec'*σ*xvec

    σ_x = sqrt(σ_x2)       # Desvio padrão dos pesos X
    
    σ_n = [σ_vec;σ_x]
    μ_n = [μ;μ_x]
    
    nome = ["Ação 1"; "Ação 2"; "Ação 3"; "Portfólio"]
    
    Gadfly.plot(x=σ_n, y=μ_n, label=nome, Coord.cartesian(xmin=0, xmax=0.2, ymin=0, ymax=0.05), 
        Guide.xlabel("σ"), Guide.ylabel("μ"), Guide.title("Ações e Portfólio"), Geom.point, Geom.label)

end

In [ ]:
a = [0.0427; 0.0015; 0.0285]
b = [0.0100 0.0018 0.0011; 0.0018 0.0109 0.0026; 0.0011 0.0026 0.0199]

grafico1(a, b)